http:
  pool:
    maxTotal: 500
    defaultMaxPerRoute: 300
    #设置连接超时时间，单位毫秒
    connectTimeout: 10000
    #http clilent中从connetcion pool中获得一个connection的超时时间,单位毫秒
    connectionRequestTimeout: 500
    #请求获取数据的超时时间，单位毫秒。 如果访问一个接口，多少时间内无法返回数据，就直接放弃此次调用
    socketTimeout: 15000
    validateAfterInactivity: 2000
spring:
  datasource:
    url: jdbc:mysql://doris01:9030/dc_ads
    username: ads_server
    password: ads_server
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      db-type: mysql
      enable: true
      initialSize: 50
      minIdle: 50
      maxActive: 500
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 'x'
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: stat,wall
      filter:
        wall:
          enabled: true
          config:
            commentAllow: true
            multiStatementAllow: true
            noneBaseStatementAllow: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js , *.gif ,*.jpg ,*.png ,*.css ,*.ico , /druid/*"
        session-stat-max-count: 1000
        profile-enable: true
        session-stat-enable: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: 123456
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1
